Module1 task1
htmlacademy-vue/53596-pizza-1 pull request #1
Opened 2021-07-24 16:30 UTC by nikolaev-dev

Первое задание:
Компонент src/frontend/src/views/Index.vue рабочий

Но, в проекте он сейчас никуда не добавлен
Как проверял его работу:

Заменял содержимое src/frontend/src/App.vue
А так же подгружал стили из templates в src/frontend/public/index.html вот в таком виде
<link rel="stylesheet" href="http://localhost:9999/css/style.min.css">

Так же немного доработал данные в data
для dough, ingredients, sizes добавил поле value, которое хранит значение для добавления к классам
<span :class="`filling filling--${item.value}`">

2021-07-26 07:05 UTC, maxim-usikov requested changes
> Импортировать данные из статических json-файлов и подключить их в опции data компонента.

Там они обновляли шаблон вроде как и докидывали файлы. Надо поискать и дообновиться: https://htmlacademy-vue.slack.com/archives/C025NBNCJ5Q/p1625583912168300

(Можно в след прах это сделать, текущий вариант - ок можем ехать, после исправлений связывания)

2021-07-26 07:05 UTC, maxim-usikov commented on src/frontend/src/views/Index.vue
> +                  value="{item.value}"
Здесь биндинг пропущен. Ты в value сейчас тут просто строку записал: `{item.value}`, а не значение

```js
// long
v-bind:value="item.value"

// short
:value="item.value"
```

2021-07-26 07:05 UTC, maxim-usikov commented on src/frontend/src/views/Index.vue
> +                  value="{item.value}"
Биндинг

2021-07-26 07:05 UTC, maxim-usikov commented on src/frontend/src/views/Index.vue
> +                      }}</span>
форматирование такое, если это автоматическое не исправляй

2021-07-27 11:39 UTC, nikolaev-dev commented
Сделал binding, исправил форматирование
часть файлов уже подправил, остальные сделаю к след уроку 


Вопрос: в задании 2 идет разбивка на компоненты, эту страничку просто оставить в App.vue ? 
Просто сейчас она есть, но нигде не используется

2021-07-27 12:21 UTC, maxim-usikov commented
> Вопрос: в задании 2 идет разбивка на компоненты, эту страничку просто оставить в App.vue ?
Просто сейчас она есть, но нигде не используется

Да

2021-07-27 12:28 UTC, maxim-usikov approved these changes

2021-07-27 12:28 UTC, merged